image_width: 1920
image_height: 1080
camera_name: logitech_c920
camera_matrix:
  rows: 3
  cols: 3
  data: [ 1385.75176,     0.     ,   964.1157 ,
             0.     ,  1388.11059,   572.11948,
             0.     ,     0.     ,     1.     ]
distortion_model: plumb_bob
camera_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.103269, -0.173374, 0.001653, 0.000164, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [ 1.,  0.,  0.,
          0.,  1.,  0.,
          0.,  0.,  1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [ 1399.78662,     0.     ,   964.70714,     0.     ,
             0.     ,  1408.9115 ,   573.26823,     0.     ,
             0.     ,     0.     ,     1.     ,     0.     ]
